### ISSUE TITLE
TextArea should be wrapped in .input-field div

### ISSUE THREAD

**Issue by tcmal** [djhi/meteor-autoform-materialize#35] opened 2015-06-11 20:59 UTC
From the materialize website:

> You must have a `.input-field` div wrapping your input and label.

**Comment by boustanihani** [comment] 2015-06-11 21:15
Possible duplicate of https://github.com/djhi/meteor-autoform-materialize/issues/34 ??

**Comment by tcmal** [comment] 2015-06-12 15:26
I don't think so...

**Comment by djhi** [comment] 2015-07-02 15:13
Can't reproduce, they are wrapped in an `.input-field`.

I might have fixed this with other changes, so please wait for `0.0.20`

**Comment by byennen** [comment] 2015-07-02 15:25
@djhi thanks for getting these PR's accepted!

**Comment by djhi** [comment] 2015-07-02 16:05
My pleasure, keep reporting any prbs ;)

**Closed as completed by djhi** 2015-07-02 16:05 UTC
