### ISSUE TITLE
Input with prepended icon does not work

### ISSUE THREAD

**Issue by justintech** [djhi/meteor-autoform-materialize#81] opened 2015-11-25 23:42 UTC
When I do a simple custom autoform trying to get icons on the fields it doesn't work:

```
<template name="insertItemForm">
    {{#autoForm collection="Items" id="insertItemForm" type="insert" class="card-panel"}}
        {{> afQuickField name="name" icon='create' }}
        {{> afQuickField name="description" type='textarea' icon='person' rows=8 }}
        <button type="submit">Submit</button>
    {{/autoForm}}
</template>
```

Anyone else have this issue/know a work around?

**Comment by shyaaam** [comment] 2016-01-20 18:36
+1.

The issue is this file.
`<template name="afIcon_materialize">
  <i class="material-icons prefix">{{this.icon}}</i>
</template>`

It should have been 
`<template name="afIcon_materialize">
  <i class="material-icons prefix {{this.icon}}"></i>
</template>`

If you do this, it gets corrected. I request the author to correct this. too lazy to do a pull request.

**Comment by acomito** [comment] 2016-07-08 13:55
mine work fine like this:

https://github.com/djhi/meteor-autoform-materialize#input-with-prepended-icon

**Comment by djhi** [comment] 2017-03-19 09:01
Future work on this package has been transferred [here](https://github.com/mozfet/meteor-autoform-materialize).

**Closed as completed by djhi** 2017-03-19 09:01 UTC
