### ISSUE TITLE
Bug: afQuickField does not save to doc

### ISSUE THREAD

**Issue by Chun-Yang** [djhi/meteor-autoform-materialize#26] opened 2015-05-28 17:48 UTC
Hi @djhi , I am enjoying you package and thank you.

I get an error described bellow. Can you take a look when you have time?

Bug demo: http://meteorpad.com/pad/kEdy34SJfEhjbiymy/Leaderboard
- click 'a1'
- click 'submit'
- NOTE areas is required error message even though a1 is selected
- NOTE at http://app-b6xirfen.meteorpad.com/, open console, the log message comes from 

```
AutoForm.addHooks(['new-campaign-1'], {
  formToDoc: function(doc) {
    console.log('doc:', doc);
    return doc;
  },
});
```
- The quick field that caused this error:

```
 {{> afQuickField
        name='areas'
        options='allowed'
        noselect=true
        label=false}}
```
- autoform itself works fine without autoform-materialize plugin.

**Comment by djhi** [comment] 2015-06-10 19:34
Seems to be fixed in 0.0.19. Not able to reproduce it

**Closed as completed by djhi** 2015-06-10 19:34 UTC
