### ISSUE TITLE
dropdown labels are too high

### ISSUE THREAD

**Issue by boustanihani** [djhi/meteor-autoform-materialize#43] opened 2015-07-09 10:54 UTC
This issue still seems to exist using v0.0.20: https://github.com/djhi/meteor-autoform-materialize/issues/31

Check: http://dropdown-labels-too-high.meteor.com/

`{{> quickForm id="tableCreate" schema="Schema.test"}}`

``` javascript
Schema.test = new SimpleSchema({

    size1: {
        type: Number,
        label: 'Size-1',
        allowedValues: [1, 2, 3, 4, 5],
    },

    size2: {
        type: Number,
        label: 'Size-2',
        allowedValues: [1, 2, 3, 4, 5],
        autoform: {
            firstOption: 'Choose Size-2',
            options: 'allowed',
        }
    },
});
```

**Comment by djhi** [comment] 2015-07-12 16:00
Please post the version of materialize you use. 

On the autoform playground, I can't reproduce your issue:

http://autoform-materialize-playground.meteor.com/
https://github.com/djhi/meteor-autoform-materialize-playground

**Comment by boustanihani** [comment] 2015-07-12 16:03
I am using the latest https://atmospherejs.com/materialize/materialize **v0.97.0**

**Comment by jholl** [comment] 2015-07-12 22:42
Looks like this is caused because of the `active` class on the label for `.select-wrapper + label`; in materialize v0.97.0 the label for a select does not need `.active` but the template `{{atts}}` are adding it.

**Comment by jholl** [comment] 2015-07-12 22:44
should note, templates `{{> afFormGroup }}` or `{{> afQuickField}}`.

**Comment by djhi** [comment] 2015-07-13 05:14
Fixed in `0.0.21` which will be released today.

**Closed as completed by djhi** 2015-07-13 05:14 UTC

**Comment by djhi** [comment] 2015-07-13 06:49
Important note I will add in README:

You must add `options: 'allowed'` to all select: see https://github.com/aldeed/meteor-autoform/issues/1086

@boustanihani, your schema must be:

``` javascript
Schema.test = new SimpleSchema({

    size1: {
        type: Number,
        label: 'Size-1',
        allowedValues: [1, 2, 3, 4, 5],
        autoform: {
            options: 'allowed', // This is needed
        }
    },

    size2: {
        type: Number,
        label: 'Size-2',
        allowedValues: [1, 2, 3, 4, 5],
        autoform: {
            firstOption: 'Choose Size-2',
            options: 'allowed',
        }
    },
});
```

**Comment by boustanihani** [comment] 2015-07-13 09:06
@djhi First thank you for the great package :)

According to https://github.com/aldeed/meteor-autoform#use-allowed-values-array-from-the-schema-as-both-the-label-and-the-value

Fields generated by quickForm or afObjectField or afArrayField **use allowedValues by default**.

Could you please calrify why you think that `options: 'allowed'` must be added?

**Comment by djhi** [comment] 2015-07-13 09:07
> see aldeed/meteor-autoform#1086

**Comment by boustanihani** [comment] 2015-07-13 09:10
Ah, you mean this is a temporary workaround until the autoform bug is fixed right?

**Comment by djhi** [comment] 2015-07-13 09:11
Right :) I'll try to submit a fix to Autoform when I'll get the chance. Feel free to make one though ;)

**Comment by boustanihani** [comment] 2015-07-13 09:13
okay I'll try :bowtie:

**Comment by jholl** [comment] 2015-07-13 19:00
Thank you very much!
